spring.application.name=FrigoService
spring.datasource.url=jdbc:postgresql://localhost:5432/EasyCook
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
server.port=8084